### ISSUE TITLE
About Contact Modular

### ISSUE THREAD

**Issue by haarias** [tranduyhung/grav-skeleton-mache#1]
I was trying to create an web using this spectacular skeleton, and everything is fine except, modular contact...from the original zip works fine, but when i create my own contact page, only shows the title and the text, not the form...please help me

**Comment by tranduyhung** [comment]
What is the content of your page and what is the page route?

**Comment by haarias** [comment]
hello again, i am trying to use the modular page as it is. 
Content:
title: Contact
menu: ContactUS

Page Route:
/inicio/_contact -> modular/contact
website route: mysite.com/#contact

Please help me , only load the text and the title

**Comment by tranduyhung** [comment]
What is the content of your inicio/modular.md

**Comment by haarias** [comment]
Thanks a lot...was my error...i just erase the form code of the inicio/modular.md  . Now is working fine, that form really send mails? can you helpme to configure that for send mails !!!
Thanks a lot

**Comment by tranduyhung** [comment]
You need to configure Email plugin, enter your SMTP credentials if you use SMTP. You can find out more about Email plugin here: http://github.com/getgrav/grav-plugin-email
